plugins:
  - jekyll-seo-tag

social:
  name: notstupid.name
  links:
    - https://www.instagram.com/notstupid.name

logo: /icon-512.png
url: https://notstupid.name

title: ""
lang: "en_US"

defaults:
  -
    scope:
      path: ""
    values:
      image: /icon-512.png
